---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-gmpfeifer-at
  namespace: default
spec:
  secretName: local-gmpfeifer-at-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.gmpfeifer.at"
  dnsNames:
  - "local.gmpfeifer.at"
  - "*.local.gmpfeifer.at"
