---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-gmpfeifer-at
  namespace: default
spec:
  secretName: test-gmpfeifer-at-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.test.gmpfeifer.at"
  dnsNames:
  - "test.gmpfeifer.at"
  - "*.test.gmpfeifer.at"
